# utils/evaluate_guess.py
from typing import Tuple


def evaluate_guess(guess: int, rnd_num: int, score: int) -> Tuple[int, str, bool]:
    """Evaluate the user's guess against the target number and provide feedback.

    :param guess: The validated integer guess from the player.
    :param rnd_num: The secret random number generated by the computer.
    :param score: The current score representing the player's remaining attempts.

    :return: A tuple containing the updated score (int), a feedback message (str),
             and a win status flag (bool).
    """
    if guess == rnd_num:
        return score, "Correct Answer!\nYou won", True

    if (score := score - 1) == 0:
        return score, "You don't have any chance.\nGame Over!", False

    if guess > rnd_num:
        return score, f"{guess} is too high", False
    else:
        return score, f"{guess} is too low", False


if __name__ == "__main__":
    evaluate_guess(50, 20, 10)
